language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.16"
  - "5.14"

install:
   - cpanm Alien::Base
   - cpanm Alien::Base::ModuleBuild
   - cpanm -v --installdeps .

script:
   - perl ./Build.PL
   - ./Build
   - rm -f Alien-ImageMagick-*.tar.gz
   - ./Build dist
   - cpanm -v Alien-ImageMagick-*.tar.gz
